from enum import StrEnum


class Location(StrEnum):
    """서울시 지역구 정보에 대한 StrEnum."""
    DoBong = "도봉구"
    NoWon = "노원구"
    GangBuk = "강북구"
    EunPyeong = "은평구"
    SeongBuk = "성북구"
    JungNang = "중랑구"
    SeoDaeMun = "서대문구"
    JongNo = "종로구"
    DongDaeMun = "동대문구"
    MaPo = "마포구"
    JungGu = "중구"
    SeongDong = "성동구"
    GwangJin = "광진구"
    YongSan = "용산구"
    GangSeo = "강서구"
    YangCheon = "양천구"
    YeongDeungPo = "영등포구"
    GuRo = "구로구"
    DongJak = "동작구"
    GeumCheon = "금천구"
    GwanAk = "관악구"
    SeoCho = "서초구"
    GangNam = "강남구"
    SongPa = "송파구"
    GangDong = "강동구"
